Repository DCC-Lab/PyTissueOptics, pull requests merged in 2021-04, with the labels that each got.

#12 cupyVectors fixed and tested
  .idea/PyTissueOptics.iml
  demoVectorsCupy.py
  pytissueoptics/scalars.py
  pytissueoptics/tests/testsVectors.py
  pytissueoptics/vectors.py
Labels: performance

#15 World is now an instance
  montecarlo.py
  pytissueoptics/__main__.py
  pytissueoptics/geometry.py
  pytissueoptics/photon.py
  pytissueoptics/stats.py
  pytissueoptics/surface.py
  pytissueoptics/world.py
  test.py
Labels: bug, enhancement

#19 Vector syntax input accepted for Numpy-like ArrayVectors
  pytissueoptics/tests/testsVectors.py
  pytissueoptics/vectors.py
Labels: bug
