Repository DCC-Lab/PyTissueOptics, pull requests merged in 2022-05, with the labels that each got.

#56 No-Interface GPU photon propagation
  pytissueoptics/rayscattering/__init__.py
  pytissueoptics/rayscattering/opencl/CLPhotons.py
  pytissueoptics/rayscattering/opencl/__init__.py
  pytissueoptics/rayscattering/opencl/example.py
  pytissueoptics/rayscattering/opencl/src/propagation.c
  pytissueoptics/rayscattering/opencl/src/random.c
  pytissueoptics/rayscattering/opencl/src/vectorOperators.c
  pytissueoptics/rayscattering/opencl/types.py
  pytissueoptics/rayscattering/photon.py
  pytissueoptics/rayscattering/source.py
  pytissueoptics/rayscattering/stats.py
  pytissueoptics/rayscattering/tests/testOpenCLKernels.py
  pytissueoptics/rayscattering/tests/testSource.py
  pytissueoptics/rayscattering/tissues/__init__.py
  pytissueoptics/rayscattering/tissues/infiniteTissue.py
  pytissueoptics/rayscattering/tissues/phantomTissue.py
  pytissueoptics/rayscattering/tissues/rayScatteringScene.py
  pytissueoptics/scene/viewer/mayavi/MayaviViewer.py
Labels: performance

#65 SolidGroupMerge objects to fix .obj imports
  examples/ex05.py
  examples/exampleFile.obj
  pytissueoptics/scene/__init__.py
  pytissueoptics/scene/examples/example3.py
  pytissueoptics/scene/geometry/primitives.py
  pytissueoptics/scene/geometry/surfaceCollection.py
  pytissueoptics/scene/loader/__init__.py
  pytissueoptics/scene/loader/loadSolid.py
  pytissueoptics/scene/loader/loader.py
  pytissueoptics/scene/loader/parsers/obj/objParser.py
  pytissueoptics/scene/loader/parsers/parser.py
  pytissueoptics/scene/solids/__init__.py
  pytissueoptics/scene/solids/solid.py
  pytissueoptics/scene/solids/solidFactory.py
  pytissueoptics/scene/tests/geometry/testSurfaceCollection.py
  pytissueoptics/scene/tests/solids/testSolid.py
  pytissueoptics/scene/tests/solids/testSolidGroup.py
Labels: bug

#72 Translate loaded models to pure triangle mesh
  pytissueoptics/scene/loader/loader.py
  pytissueoptics/scene/tests/loader/parsers/objFiles/testCubeTrianglesMulti.obj
  pytissueoptics/scene/tests/loader/testLoader.py
Labels: bug

#70 add a stackedCuboid example with 3 layers.
  examples/ex04.py
Labels: documentation

#73 Verifications and cleaning
  README.md
  examples/ex01.py
  examples/ex02.py
  examples/ex03.py
  examples/ex04.py
  examples/ex05.py
  examples/exampleFile.obj
  pytissueoptics/rayscattering/__init__.py
  pytissueoptics/rayscattering/example.py
  pytissueoptics/rayscattering/opencl/example.py
  pytissueoptics/rayscattering/source.py
  pytissueoptics/rayscattering/stats.py
  pytissueoptics/rayscattering/tests/testRayScatteringScene.py
  pytissueoptics/rayscattering/tests/testSource.py
  pytissueoptics/rayscattering/tissues/rayScatteringScene.py
  pytissueoptics/scene/examples/droid.obj
  pytissueoptics/scene/examples/example0.py
  pytissueoptics/scene/examples/example3.py
  pytissueoptics/scene/geometry/bbox.py
  pytissueoptics/scene/geometry/vector.py
  pytissueoptics/scene/loader/loadSolid.py
  pytissueoptics/scene/loader/loader.py
  pytissueoptics/scene/loader/parsers/obj/objParser.py
  pytissueoptics/scene/loader/parsers/parser.py
  pytissueoptics/scene/logger/logger.py
  pytissueoptics/scene/solids/solid.py
  pytissueoptics/scene/solids/solidFactory.py
  pytissueoptics/scene/tests/loader/parsers/objFiles/droid.obj
  pytissueoptics/scene/tests/loader/parsers/testOBJParser.py
  pytissueoptics/scene/tests/loader/testLoader.py
  pytissueoptics/scene/utils/__init__.py
  pytissueoptics/scene/utils/progressBar.py
Labels: documentation, enhancement
